#!/bin/bash
set -euo pipefail

# Configuration
UNIQUE_SUFFIX=$(echo "${PROJECT_ID:-$(openssl rand -hex 4)}" | cut -c1-8)
BUCKET_NAME="hso-tfstate-${UNIQUE_SUFFIX}"
REGION=$(scw config get default-region)
PROJECT_ID=$(scw config get default-project-id)

# Validate configuration
if [ -z "${REGION}" ] || [ -z "${PROJECT_ID}" ]; then
    echo -e "${RED}Error: Scaleway CLI not properly configured${NC}"
    echo "Run: scw init"
    exit 1
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}=== Openclaw Terraform Remote State Bootstrap ===${NC}\n"

# Check prerequisites
if ! command -v scw &> /dev/null; then
    echo -e "${RED}Error: Scaleway CLI (scw) not found${NC}"
    echo "Install: https://github.com/scaleway/scaleway-cli"
    exit 1
fi

# Get credentials from scw config
SCW_ACCESS_KEY=$(scw config get access-key)
SCW_SECRET_KEY=$(scw config get secret-key)

# Check authentication
if [ -z "${SCW_ACCESS_KEY}" ] || [ -z "${SCW_SECRET_KEY}" ]; then
    echo -e "${RED}Error: Scaleway credentials not found${NC}"
    echo "Run: scw init"
    exit 1
fi

echo -e "${GREEN}✓${NC} Scaleway CLI configured"
echo -e "Region: ${REGION}"
echo -e "Project: ${PROJECT_ID}\n"

# Create Object Storage bucket for Terraform state
echo -e "${YELLOW}Creating Object Storage bucket: ${BUCKET_NAME}${NC}"

# Check if bucket already exists
if scw object bucket list region=${REGION} 2>/dev/null | grep -q "${BUCKET_NAME}"; then
    echo -e "${YELLOW}⚠${NC}  Bucket already exists, skipping creation"
else
    scw object bucket create ${BUCKET_NAME} region=${REGION}

    echo -e "${GREEN}✓${NC} Bucket created successfully"
fi

# Enable versioning for state file protection
echo -e "\n${YELLOW}Enabling bucket versioning${NC}"
scw object bucket update ${BUCKET_NAME} region=${REGION} enable-versioning=true || true

echo -e "${GREEN}✓${NC} Versioning enabled"

# Create a separate bucket for backups
BACKUP_BUCKET="hso-backups-${UNIQUE_SUFFIX}"
echo -e "\n${YELLOW}Creating backup bucket: ${BACKUP_BUCKET}${NC}"

if scw object bucket list region=${REGION} 2>/dev/null | grep -q "${BACKUP_BUCKET}"; then
    echo -e "${YELLOW}⚠${NC}  Backup bucket already exists"
else
    scw object bucket create ${BACKUP_BUCKET} region=${REGION}

    echo -e "${GREEN}✓${NC} Backup bucket created"
fi

# Configure lifecycle policy for backups (30-day retention for old versions)
echo -e "\n${YELLOW}Configuring backup retention policy${NC}"
cat > /tmp/lifecycle-policy.json <<EOF
{
  "rules": [
    {
      "id": "delete-old-backups",
      "status": "Enabled",
      "expiration": {
        "days": 90
      }
    }
  ]
}
EOF

# Note: Scaleway may not support lifecycle policies yet, this is future-proofing
echo -e "${YELLOW}⚠${NC}  Lifecycle policies may require manual configuration in console"

# Generate backend configuration for Terraform
echo -e "\n${YELLOW}Generating Terraform backend configuration${NC}"

cat > ../backend-config.tf <<EOF
# This file is auto-generated by bootstrap/init-remote-state.sh
# DO NOT edit manually

terraform {
  backend "s3" {
    bucket                      = "${BUCKET_NAME}"
    key                         = "openclaw/terraform.tfstate"
    region                      = "${REGION}"
    endpoint                    = "https://s3.${REGION}.scw.cloud"
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
  }
}
EOF

echo -e "${GREEN}✓${NC} Backend configuration written to ../backend-config.tf"

# Create .env file for credentials (gitignored)
echo -e "\n${YELLOW}Creating credentials file${NC}"
cat > ../.env.terraform <<EOF
# Terraform credentials - DO NOT COMMIT
# Source this file: source .env.terraform

export SCW_ACCESS_KEY="${SCW_ACCESS_KEY}"
export SCW_SECRET_KEY="${SCW_SECRET_KEY}"
export SCW_DEFAULT_PROJECT_ID="${PROJECT_ID}"

# For S3 backend
export AWS_ACCESS_KEY_ID="${SCW_ACCESS_KEY}"
export AWS_SECRET_ACCESS_KEY="${SCW_SECRET_KEY}"

# Terraform variables (avoids being prompted during plan/apply)
export TF_VAR_tailscale_auth_key="tskey-auth-REPLACE_ME"
export TF_VAR_signal_alert_number="+REPLACE_ME"
export TF_VAR_openclaw_gateway_token="REPLACE_ME"
export TF_VAR_anthropic_api_key="REPLACE_ME"
export TF_VAR_openai_api_key="REPLACE_ME"
export TF_VAR_telegram_bot_token="REPLACE_ME"
export TF_VAR_github_token="REPLACE_ME"
export TF_VAR_squid_extra_domains='[]'
EOF

chmod 600 ../.env.terraform
echo -e "${GREEN}✓${NC} Credentials saved to ../.env.terraform (chmod 600)"

# Summary
echo -e "\n${GREEN}=== Bootstrap Complete ===${NC}\n"
echo "Resources created:"
echo "  • S3 bucket: ${BUCKET_NAME} (Terraform state)"
echo "  • S3 bucket: ${BACKUP_BUCKET} (Server backups)"
echo ""
echo "Next steps:"
echo "  1. Copy terraform.tfvars.example to terraform.tfvars"
echo "  2. Set backup_bucket_name = \"${BACKUP_BUCKET}\" in terraform.tfvars"
echo "  3. Fill in your other values (admin_username, etc.)"
echo "  4. Run: cd .. && source .env.terraform"
echo "  5. Run: terraform init"
echo "  6. Run: terraform plan"
echo "  7. Run: terraform apply"
echo ""
echo -e "${YELLOW}⚠${NC}  Keep .env.terraform secure - it contains credentials"
